server:
  port: 8901
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
spring:
  application:
    name: microservice-consumer-movie-ribbon-with-hystrix
management.endpoints.web.exposure.include: hystrix.stream