spring:
  security:
    user:
      name: user
      password: 123456
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false